name: Quantum DCA Strategy

on:
  workflow_dispatch:

jobs:
  run-dca-strategy:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: Python telepítése
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: 'pip'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-


      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Script futtatása
        run: python main.py
