name: Quantum DCA Strategy

on:
  workflow_dispatch:

jobs:
  run-dca-strategy:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v4

      - name: Python telepítése
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Függőségek telepítése
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Script futtatása
        run: python main.py
