name: Run EUR Rate Script

on:
  push:
    paths:
      - 'eur_rate.py'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Kód letöltése
        uses: actions/checkout@v3

      - name: Python beállítása
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Kötelező csomagok telepítése
        run: pip install requests

      - name: Script futtatása
        run: python eur_rate.py

